knp_paginator:
  convert_exception: false
  page_range: 5
  remove_first_page_param: false
  default_options:
    page_name: page
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
    filter_field_name: filterField
    filter_value_name: filterValue
    page_out_of_range: ignore
    default_limit: 10